### ISSUE TITLE
 python update.py uk all

### ISSUE THREAD

**Issue by Pryanic** [kmike/pymorphy2-dicts#5]
Не может создать украинский словарь 

> Downloading and converting LanguageTool dictionary...
> Traceback (most recent call last):
>   File "update.py", line 129, in <module>
>     builder.download()
>   File "update.py", line 80, in download
>     subprocess.check_call(['lt_convert.py', UK_DICT_URL, UK_DICT_XML])
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 535, in check_call
>     retcode = call(*popenargs, **kwargs)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
>     return Popen(*popenargs, **kwargs).wait()
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
>     errread, errwrite)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
>     raise child_exception
> OSError: [Errno 20] Not a directory

Что делать?

**Comment by bzaar** [comment]
Поддерживаю. [Ссылка на словарь](https://drive.google.com/uc?id=0B4mUAylazDVbUXFIRGJ2S01ibGM&export=download) в исходниках нерабочая, выдает 404. Что это за словарь, где его найти?
